name: build and push image to dockerhub
on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: Get the version
        id: get-version-release
        run: echo "version=${GITHUB_REF_NAME#refs/heads}" >> $GITHUB_ENV

      - name: Checkout to version
        uses: actions/checkout@v3
        with:
          ref: ${{ env.version }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          tags: |
            onaio/dirt-tile-server:${{ env.version }}

      - name: Image digest
        run: echo ${{ steps.docker-build.outputs.digest }}
